# Generated by Django 5.2.8 on 2025-11-13 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_delivery_time', models.CharField(blank=True, max_length=50)),
                ('budget_range', models.CharField(blank=True, choices=[('low', 'Budget ($-$$)'), ('medium', 'Moderate ($$-$$$)'), ('high', 'Premium ($$$+)')], max_length=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('favorite_restaurants', models.JSONField(blank=True, default=list)),
                ('membership_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('membership_expires', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('has_insulated_bag', models.BooleanField(default=False)),
                ('has_gps_device', models.BooleanField(default=True)),
                ('drivers_license_number', models.CharField(max_length=50, unique=True)),
                ('insurance_policy', models.CharField(blank=True, max_length=100)),
                ('vehicle_registration', models.CharField(blank=True, max_length=100)),
                ('available_hours', models.JSONField(blank=True, default=dict)),
                ('preferred_zones', models.JSONField(blank=True, default=list)),
                ('max_deliveries_per_hour', models.IntegerField(default=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('average_delivery_time', models.IntegerField(default=30, help_text='Average time in minutes')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_online', models.BooleanField(default=False)),
                ('current_location', models.JSONField(blank=True, default=dict)),
                ('current_orders', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(choices=[('chef', 'Chef'), ('sous_chef', 'Sous Chef'), ('cook', 'Cook'), ('server', 'Server'), ('host', 'Host/Hostess'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('cashier', 'Cashier'), ('bartender', 'Bartender'), ('dishwasher', 'Dishwasher'), ('cleaner', 'Cleaner'), ('owner', 'Owner')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('shift_pattern', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('seasonal', 'Seasonal')], max_length=20)),
                ('work_schedule', models.JSONField(blank=True, default=dict)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('can_process_orders', models.BooleanField(default=False)),
                ('can_handle_payments', models.BooleanField(default=False)),
                ('can_modify_menu', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('performance_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('training_completed', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID'), ('state_id', 'State ID')], max_length=30)),
                ('identity_document_number', models.CharField(blank=True, max_length=50)),
                ('identity_document_verified', models.BooleanField(default=False)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('business_license_verified', models.BooleanField(default=False)),
                ('tax_id_verified', models.BooleanField(default=False)),
                ('food_safety_verified', models.BooleanField(default=False)),
                ('background_check_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('expired', 'Expired')], default='not_required', max_length=20)),
                ('background_check_date', models.DateField(blank=True, null=True)),
                ('bank_account_verified', models.BooleanField(default=False)),
                ('payment_method_verified', models.BooleanField(default=False)),
                ('fully_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('food_truck', 'Food Truck'), ('catering', 'Catering Service'), ('bakery', 'Bakery'), ('grocery', 'Grocery Store')], max_length=50)),
                ('business_description', models.TextField(blank=True)),
                ('business_registration_number', models.CharField(max_length=100, unique=True)),
                ('food_safety_certification', models.CharField(blank=True, max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('cuisine_specialties', models.JSONField(blank=True, default=list)),
                ('service_areas', models.JSONField(blank=True, default=list)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('payout_schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('average_preparation_time', models.IntegerField(default=30, help_text='Average time in minutes')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Verification'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='background_check_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_info',
            field=models.JSONField(blank=True, default=dict, help_text='Encrypted bank account information'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_addresses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_radius',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Delivery radius in kilometers', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Food Vendor'), ('delivery', 'Delivery Service Provider'), ('restaurant_staff', 'Restaurant Staff'), ('restaurant_manager', 'Restaurant Manager'), ('restaurant_owner', 'Restaurant Owner'), ('platform_admin', 'Platform Administrator'), ('support_agent', 'Customer Support Agent'), ('content_moderator', 'Content Moderator'), ('marketing_specialist', 'Marketing Specialist'), ('finance_manager', 'Finance Manager'), ('data_analyst', 'Data Analyst')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professional_summary',
            field=models.TextField(blank=True, help_text='Professional experience summary'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spice_tolerance',
            field=models.IntegerField(default=0, help_text='Scale of 1-5, 0 for not specified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list, help_text='List of dietary preferences'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='accounts_cu_user_ty_97b0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['account_status'], name='accounts_cu_account_eb20fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='accounts_cu_created_35a2d8_idx'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='accounts_userprofile',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type__in': ['restaurant_staff', 'restaurant_manager', 'restaurant_owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'platform_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
