# Generated by Django 5.2.7 on 2025-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_deliveryprofile_staffprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('low', 'Budget (GHC-GHC GHC)'), ('medium', 'Moderate (GHC GHC-GHC GHC GHC)'), ('high', 'Premium (GHC GHC GHC+)')], max_length=20),
        ),
    ]
