# Generated by Django 5.2.7 on 2025-12-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customerprofile_budget_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverification",
            name="code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userverification",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="userverification",
            name="phone_verification_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
