# Generated by Django 5.2.7 on 2025-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='meal_period',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('supper', 'Supper'), ('dinner', 'Dinner'), ('all_day', 'All Day')], default='all_day', max_length=20),
        ),
    ]
