# Generated by Django 5.2.7 on 2025-11-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menucategory_meal_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=2.99, help_text='Delivery fee in GHC', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(default='30-45 min', help_text='Estimated delivery time', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Minimum order amount in GHC', max_digits=8),
        ),
    ]
