# Generated by Django 5.2.8 on 2025-11-19 05:18

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slug(base, existing_slugs):
    base_slug = slugify(base) or "item"
    candidate = base_slug
    idx = 1
    while candidate in existing_slugs:
        idx += 1
        candidate = f"{base_slug}-{idx}"
    existing_slugs.add(candidate)
    return candidate


def forwards_func(apps, schema_editor):
    Restaurant = apps.get_model('restaurants', 'Restaurant')
    MenuItem = apps.get_model('restaurants', 'MenuItem')

    # Backfill Restaurant slugs
    existing_restaurant_slugs = set(
        Restaurant.objects.exclude(slug__isnull=True).exclude(slug__exact="").values_list('slug', flat=True)
    )
    for r in Restaurant.objects.all():
        if not r.slug:
            r.slug = generate_unique_slug(r.name or "restaurant", existing_restaurant_slugs)
            r.save(update_fields=['slug'])

    # Backfill MenuItem slugs
    existing_item_slugs = set(
        MenuItem.objects.exclude(slug__isnull=True).exclude(slug__exact="").values_list('slug', flat=True)
    )
    for m in MenuItem.objects.select_related('restaurant').all():
        if not m.slug:
            base_parts = []
            if getattr(m, 'restaurant', None) and getattr(m.restaurant, 'name', None):
                base_parts.append(m.restaurant.name)
            base_parts.append(m.name or "menu-item")
            m.slug = generate_unique_slug("-".join(base_parts), existing_item_slugs)
            m.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0003_restaurant_delivery_fee_restaurant_delivery_time_and_more",
        ),
    ]

    operations = [
        # Add fields initially without unique constraint to allow backfill
        migrations.AddField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        # Enforce uniqueness after data is populated
        migrations.AlterField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
