# Generated by Django 5.2.7 on 2025-11-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menuitem_slug_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_categories/'),
        ),
    ]
