# Generated by Django 5.2.7 on 2025-11-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_menucategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='prep_time',
            field=models.IntegerField(blank=True, default=0, help_text='Preparation time in minutes', null=True),
        ),
    ]
