# Generated by Django 5.2.7 on 2025-11-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_menuitem_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.JSONField(default=list, help_text='List of ingredients as objects: [{name, quantity, unit, notes}]'),
        ),
    ]
